### ISSUE TITLE
Hyphenated words

### ISSUE THREAD

**Issue by Nukesor** [elijah-potter/harper#101]
First of all, thanks for trying to tackle this problem :)

I played around a bit with harper and one issue I stumbled upon pretty quickly is hyphens.

For example, `pre-existing` is not in the dictionary, but it's also not possible to add it to the dictionary, as `pre` is detected as its own word.

It seems that there's currently no support for well-known hyphenated phrases.

**Comment by elijah-potter** [comment]
This should actually be a pretty quick and straightforward fix. I'll give an update here once a release is pushed out. Thanks for letting me know!

**Comment by elijah-potter** [comment]
The changes are made, but I am a little hesitant to create a release until the changes I've got stashed are finished. As before, I'll update here once it's truly ready.

**Comment by elijah-potter** [comment]
Alright there's a release with the tentative changes available now. Do me a favor and try out some other hyphenated words? We may need to expand the dictionary a bit.

**Comment by elijah-potter** [comment]
As per #107 this _has_ turned out to be more complex. I've decided that the prefix should remain it's own token. These prefixes just need to be added to the dictionary as necessary. If there are any other prefixes that need to be added, please feel free to reopen this ticket and I'll make the changes promptly.
