### ISSUE TITLE
What is the name origin?

### ISSUE THREAD

**Issue by Dich0tomy** [elijah-potter/harper#103]
Hey! I hope I am not disrupting your flow, this is not an important question!

First of all, the project is great - upon sharing it with a few friends of mine we started a heated debate about the origin of the name, from the many theories the most popular one was "it's just a pretty name", hence the question - how did you come up with the name? Is there some poetic allegory behind it or is it just that you found `harper` to be a pretty and suitable name for the project?

Once again, sorry if I'm disrupting the flow, but `Discussions` aren't enabled on this repo and I worry my curiosity *is* going to kill me ;D

Have a nice day!

**Comment by elijah-potter** [comment]
You are absolutely not interrupting the flow. I hadn't realized `Discussions` were off. They should be available now.

To answer your question though: when I first sat down to start work on Harper, I had one goal in mind.
I wanted to create a grammar checker that wouldn't impinge on the artistic freedom of authors.
Part of that meant that I did not want literary devices to flagged as grammatical errors.
Harper should up the writing process rather than slow it down as Grammarly tends to.

To embody this original goal, I wanted to make the project a namesake of an author known for their literary devices and prose. I also had three other (practical) criterion:


1. It could not be occupied on [crates.io](https://crates.io/).
1. It could not be occupied on GitHub.
1. It should not be more than two syllables.

I asked around for some ideas and someone suggested I name the project after [Harper Lee](https://en.wikipedia.org/wiki/Harper_Lee).
It fit the bill, so I went with it.

**Comment by Dich0tomy** [comment]
Thank you for the thorough explanation. Have a great day!

**Comment by adrian5** [comment]
Elijah, I was reading the FAQ on [Naming Harper](https://elijahpotter.dev/articles/naming_harper) and I think there might be a word missing:

> Part of that meant that I did not want literary devices to flagged as grammatical errors

Thanks for creating this wonderful tool, it's incredibly fast compared to the alternatives!

**Comment by elijah-potter** [comment]
Excellent eye! I'll add a rule to Harper to catch future cases like that.
