### ISSUE TITLE
bug: hyphenated adjectives marked wrong

### ISSUE THREAD

**Issue by Agent-E11** [elijah-potter/harper#107]
Now that "harper recognizes hyphenated words as single tokens", hyphenated adjectives are flagged:

```
short-term
first-time
long-distance
Spanish-speaking
sun-dried
second-place
four-wheel
```

I actually can't even think of any words that it doesn't flag. Even `non-null`, the example given in the release notes, doesn't work.

Personally, I prefer the old way, where it just checked the individual words.

**Comment by elijah-potter** [comment]
I actually entirely agree. I wanted to try the hyphenating "fix" for the sake of completeness, but there are simply too many combinations to add to the dictionary. I'll push out a release asap, undoing the change.

**Comment by elijah-potter** [comment]
I just want to say that I really appreciate your issues @Agent-E11. You've actually been a huge help. I've reverted the changes. As it turns out, pre should actually be it's own word, it just can only be used in certain grammatical contexts. As I mentioned in #101, if there are any other prefixes that should be added to Harper's dictionary, reopen the ticket and I'll make the changes.

**Comment by Agent-E11** [comment]
Thanks 😄 I do really like this LSP by the way
