### ISSUE TITLE
Zed extension

### ISSUE THREAD

**Issue by Feel-ix-343** [elijah-potter/harper#167]

**Comment by lukasmwerner** [comment]
There is a community extension being built [Stef16Robbe/harper_zed](https://github.com/Stef16Robbe/harper_zed). From what I can tell it just needs to be merged in the Zed extensions repo see zed-industries/extensions#1404

**Comment by elijah-potter** [comment]
@Stef16Robbe throw us an update here once it get's merged. Thank you so much for your great work!

**Comment by Stef16Robbe** [comment]
Got merged! Ready for anyone to try out. @elijah-potter what's the best way for me to stay up-to-date with new languages being supported by Harper? I guess keeping an eye on new releases?

**Comment by elijah-potter** [comment]
That's fantastic. The current source-of-truth is [the Neovim config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/harper_ls.lua). Otherwise, new language support will be mentioned in the release notes, yes.

I'm going close this issue since everything looks good here.

**Comment by Feel-ix-343** [comment]
cooooollll
