### ISSUE TITLE
Windows GitHub Actions builds missing dependency

### ISSUE THREAD

**Issue by elijah-potter** [elijah-potter/harper#208]
Downloading the `harper-ls` binary for Windows and running it throws an error complaining about the absence of a `libstdc++-6.dll` file. Not sure how long this has been happening, but it's a major issue that needs to be dealt with before #200 can happen.

**Comment by mcecode** [comment]
So I got interested in this and experimented a bit. Seems like changing our build target on Windows from `x86_64-pc-windows-gnu` to `x86_64-pc-windows-msvc` fixes the problem, probably because MSVC is the default on Windows and is therefore more widely available.

Here's a sample run I did with an artifact you can try out: https://github.com/mcecode/harper/actions/runs/11242681556

**Comment by elijah-potter** [comment]
Would you mind opening a pull request to fix the Release job for this? Thanks for figuring that out.
